### ISSUE TITLE
另外再请问一下低版本的RN，有可用的吗？ 例如 0.30.0

### ISSUE THREAD

**Issue by daffy6537** [yorkie/react-native-wechat#198]
RT

**Comment by daffy6537** [comment]
npm WARN react-native-wechat@1.9.2 requires a peer of react-native@>=0.40 but none was installed.

**Comment by lhaiqing** [comment]
同样这个问题求解。

**Comment by yorkie** [comment]
0.30.x 是不支持的，对与0.35以上的版本可以用react-native-wechat@1.8.0：https://github.com/yorkie/react-native-wechat/blob/cabc84253fd2d85cb0267668eb06cb164f3d2899/package.json
