### ISSUE TITLE
无法打开授权页面

### ISSUE THREAD

**Issue by Sura-zm** [yorkie/react-native-wechat#207]
调用
WeChat.sendAuthRequest("snsapi_userinfo")
没有弹出授权页面
react@15.4.2
react-native@0.41.2
react-native-wechat@1.9.2

**Comment by yorkie** [comment]
可能是签名的问题，什么平台？

**Comment by Sura-zm** [comment]
问题解决了，谢谢

**Comment by Vinkugor** [comment]
@Sura-zm 怎么解决的能说一下吗？🙏

**Comment by Vinkugor** [comment]
@yorkie 签名是什么签名？APP签名？
