### ISSUE TITLE
react0.40版本出错： undefined is not an object (evaluating '_reactNative Wechat2.default.registerApp')

### ISSUE THREAD

**Issue by blade770** [yorkie/react-native-wechat#208]
引用：为import WeChat from 'react-native-wechat'; 
但是到注册应用时就会报这样的错误：undefined is not an object (evaluating '_reactNative Wechat2.default.registerApp')
react-native@0.40.0
react-native-wechat@1.9.2
求解

**Comment by yorkie** [comment]
可以重新安装并 `react-native link` 一下～

**Comment by blade770** [comment]
重新安装过了，还是这样……

**Comment by nukc** [comment]
```js
import * as WeChat from 'react-native-wechat';
```

**Comment by blade770** [comment]
OK, 使用nukc 提供的方法可以正常使用了，thanks。
~~~
import * as WeChat from 'react-native-wechat';
~~~

**Comment by holin** [comment]
我碰到类似问题。
undefined is not an object (evaluating 'Wechat.registerApp')
react-native@0.46.3
react-native-wechat@1.9.9

<img width="624" alt="screen shot 2017-07-19 at 5 27 36 pm" src="https://user-images.githubusercontent.com/1019/28360301-a3117326-6ca7-11e7-9d7a-679122e5fe98.png">

**Comment by hwmiao** [comment]
I encountered the same problem
react-native link react-native-wechat didnt work
just manual link

**Comment by hms111111** [comment]
null is not an object (evaluating 'WeChat.registerApp')
