### ISSUE TITLE
有没有历史版本相关信息？ Any information about release history?

### ISSUE THREAD

**Issue by orbit-dna** [yorkie/react-native-wechat#211]
遇到了一个 “React/RCTBridgeModule.h file not found“ 的问题。
当然了，这是一个版本的问题。相关问题 #174。
因为种种原因，暂时不方便升级 react-native 4.0，所以想安装一个合适的版本。但是在 branch，tag，以及 npm 网站中均未发现版本相关信息。

所以有一个问题，就是能不能在 README 加一些版本信息，或者在 release 的时候打个 tag 什么的。
另外，似乎适用于 react-native 4.0 以下的最高版本是 1.8.0。

**Comment by yorkie** [comment]
这个应该一般是配置问题，另外可以试试`1.8.*`

**Comment by orbit-dna** [comment]
是的，是版本的问题。
当时是想找一个适用于 RN 4.0 以下的这个包的最高版本，但是没有找到直接的关于版本的文档，于是就问了一下。
