### ISSUE TITLE
Should api reject an Error Object?

### ISSUE THREAD

**Issue by hitbear518** [yorkie/react-native-wechat#217]
While using shareToSession, if I click close button in Wechat, I got a waring: `a promise was rejected with a non-error: [object Number]`, I figured out that it rejected -2, which correspond to `WXErrCodeUserCancel = -2,   /**< 用户点击取消并返回    */`, so should this kind of api reject an Error Object?
![image](https://cloud.githubusercontent.com/assets/5070531/26689685/15e72d5e-4729-11e7-991f-a5e5be71e96d.png)

使用 shareToSession api 时，如果点击微信左上角的关闭，promise 会 reject -2，这里需要改成 reject Error 对象吗？

**Comment by anjianshi** [comment]
Promise 规范其实并没有要求必须 reject Error 对象，不过为了便于排查问题，一些类库例如 bluebird 会要求 reject Error 对象。
可以考虑自定义一个 Error 对象，这样也确实更便于调试。
```
function WechatError(code) {
    this.code = code
    this.message = 'wechat error ' + code
}
WechatError.prototype = Error.prototype
```

**Comment by yorkie** [comment]
+1 @hitbear518 可以提个PR吗？

**Comment by anjianshi** [comment]
@yorkie 感觉在错误处理方面的设计有点不清晰啊。

README 里介绍 sendAuthRequest 等接口的返回值时，说 errCode 为 0 代表操作成功，如果失败了则可以通过 errStr 读取失败信息。

这样说，就暗示使用者应该通过 errCode 来判断操作是否成功，使用者也会想当然觉得不需要通过 promise.catch() 来捕获这类错误。

但按照当前的实现，使用者其实应该通过 promise.catch() 来捕获错误，而不是在 promise.then() 里读取 errCode。这一点在 README 里好像没有

但其实，当 errCode 不为 0 时，promise 压根不会 resolve，而是会 reject，

**Comment by anjianshi** [comment]
@yorkie 感觉在错误处理方面的设计有点不清晰啊。

README 里介绍 sendAuthRequest 等接口的返回值时，说 errCode 为 0 代表操作成功，如果失败了则可以通过 errStr 读取失败信息。

这样说，就暗示使用者应该通过 errCode 来判断操作是否成功，使用者也会想当然觉得不需要通过 promise.catch() 来捕获这类错误。

但按照当前的实现，使用者其实应该通过 promise.catch() 来捕获错误，而不是在 promise.then() 里读取 errCode。
这一点在 README 里没有说明。虽然示例代码里是通过 catch 来捕获错误的，但用户未必想到这里捕获到的错误就是因 errCode 不为 0 而抛出的错误，他可能会以为这个 catch 只是用来处理一些不可预见的意外情况。（我就一直是这么以为的，直到看了 react-native-wechat 的实现代码）

是否可以调整一下，干脆在 errCode 不为 0 时也正常 resolve promise？

**Comment by yorkie** [comment]
这个问题确实存在，原因是之前在 #136 没有对文档也做出对应的更新，多谢提醒，一会更新下文档 :)
