### ISSUE TITLE
分享到朋友圈，thumbImage参数并不支持ios端resource id图片的展示啊！

### ISSUE THREAD

**Issue by shenhua123** [yorkie/react-native-wechat#221]
如题，看了源码，发现thumbImage参数只支持获取网络图片，跟描述的支持resource id不符

**Comment by wangweifeng66** [comment]
使用resolveResetSource 处理一下require的本地路径就可以了
demo里面有 eg: thumbImage: resolveAssetSource(require(./image/a.png)).uri
