### ISSUE TITLE
微信分享 WeChat.shareToTimeline 或者 WeChat.shareToSession 调不起来微信，授权登录没问题

### ISSUE THREAD

**Issue by Calvin92** [yorkie/react-native-wechat#223]
如题，授权登录是好的，按理说签名不会有问题，
但是 分享的两个方法执行后调不起来微信，既不进入resolve也不进入reject回调。。

**Comment by yorkie** [comment]
提Bug的时候附带一下平台及相关版本号

**Comment by Calvin92** [comment]
@yorkie 
sorry, 疏忽了～
安卓6.0
react-native-wechat： 1.9.2

**Comment by yorkie** [comment]
`WXEntryActivity.java`是正确的吗？

**Comment by Calvin92** [comment]
正确的  我很纳闷为什么授权登录都好好的   分享就是调不起来～
这是我的WXEntryActivity.java    我前几天还好好的  
![2017-06-12 14 14 07](https://user-images.githubusercontent.com/12781397/27021252-b5b14934-4f79-11e7-8353-9bdfba6acbfe.png)

**Comment by yorkie** [comment]
> 这是我的WXEntryActivity.java 我前几天还好好的

如果是突然不好的话，一般就是签名问题了，重新确认下签名并且重新打包一次试试看吧。

**Comment by Calvin92** [comment]
是thumbImage的问题， 不知道什么原因， 好像thumImage参数如果不是图片地址，在安卓直接调不起来

**Comment by ResponseState200** [comment]
@IceTeddy 您好,请问您是怎么修复好的,能否提供一下代码示例,我也遇到了同样的问题
