### ISSUE TITLE
globalObject.hasOwnProperty错误

### ISSUE THREAD

**Issue by Txiaozhe** [yorkie/react-native-wechat#226]
react-native版本：0.43.3
react-native-wechat版本：1.9.0
测试机型：红米note2
错误描述：ios版本能正常编译并执行打开微信、请求权限等操作，但在android 真机上出现这个错误，一打开就闪退，这是网上找的图，跟我一模一样的错误，这是一篇react-native issues说明该问题的文档
[react-native/issues/12823](https://github.com/facebook/react-native/issues/12823)
![err](https://cloud.githubusercontent.com/assets/4250838/23743508/d5ce6644-04eb-11e7-899e-a7faf11abd93.png)

**Comment by Txiaozhe** [comment]
已找到解决方案：打开node_modules/es6-promisify/dist/promise.js     第31行：改成如下所示代码
```javascript
        if ((globalObject === undefined) || (globalObject.hasOwnProperty === undefined) || !globalObject.hasOwnProperty("Promise")) {
```
但这只是暂时解决，且无法同步到代码仓库，因此每次clone后重新编译前需先做以上更改。仍然希望作者能做兼容性修复。

**Comment by yorkie** [comment]
谢谢，不过这个问题已经在 v1.9.2 以后的版本修复了，可以更新一下版本～

**Comment by yorkie** [comment]
具体的 commit 是：https://github.com/yorkie/react-native-wechat/commit/434761b4d77c8b3ad4ca629ba9cb7d11b0b659e9

**Comment by Txiaozhe** [comment]
好，谢谢您。

**Comment by yorkie** [comment]
:)
