### ISSUE TITLE
安卓调用分享API，返回错误码-6，表示什么错误？

### ISSUE THREAD

**Issue by spenghang** [yorkie/react-native-wechat#227]

**Comment by WHZWHZ1229** [comment]
同样遇到这个问题

**Comment by ldzdz** [comment]
是因为你的 签名 有问题 去微信看下的应用签名

**Comment by yorkie** [comment]
谢谢 @ldzdz

**Comment by Y-JH** [comment]
这个问题，已经解决！现在和同学们分享下我的经历：
问题重现：点击分享，弹出微信的分享入口，让我选择进行分享。但是却无法唤起微信的应用页面，就跟闪退一样。然后我打印了日志，说 "-6"  。
问题出现原因：你的“应用签名”一定是填写错误。
解决方案：到微信开发平台下载一个apk——GenSignature ，分别对自己的应用安装到手机上debug版、release版，并在软件中输入包名，查看正确的应用签名，并放到微信开放平台进行测试。当然，即使后来填写的都对，也许也不能正确的唤起微信，这时候有一个奇葩的操作就是"重启手机"，别问我为什么，我的手机就需要这样才行！！

**Comment by volonkou** [comment]
同样的代码，我在debug状态下可以正常分享，但是在release状态下就提示签名不对
