### ISSUE TITLE
分享图片时，description 没有填入到微信的文本输入框里面，只有图片

### ISSUE THREAD

**Issue by hongshu123** [yorkie/react-native-wechat#229]

**Comment by yorkie** [comment]
请给出代码和截图，这样方便分析问题

**Comment by mantou132** [comment]
同样的问题，
```
WeChat.shareToTimeline({
        type: 'news', 
        webpageUrl: data.url,
        description: data.text || data.title, // 'tests2341'
        thumbImage: data.imageUrl
      }).catch(console.log);
```

**Comment by mantou132** [comment]
我的问题解决了：
https://github.com/yorkie/react-native-wechat#class-sharemetadata

sharemetadata 中必须要写 title。
description 没用

**Comment by cnpmge** [comment]
> 我的问题解决了：
> https://github.com/yorkie/react-native-wechat#class-sharemetadata
> 
> sharemetadata 中必须要写 title。
> description 没用

请问怎样解决的？
