### ISSUE TITLE
android 一直返回 “WeChap API invoke returns false”  IOS没问题

### ISSUE THREAD

**Issue by ss7247** [yorkie/react-native-wechat#233]
按照 官方的配置  配了，用 android 一直返回 “WeChap API invoke returns false”

**Comment by ss7247** [comment]
调的是微信支付   WeChat.pay

**Comment by yorkie** [comment]
参数错误，或者签名问题 :)

**Comment by ss7247** [comment]
@yorkie   我同样的参数，在IOS能调起来，在android 这边就这样，有时候直接闪一下就过了，没有任何错误提示

**Comment by ss7247** [comment]
看了下源码，这个错误提示是插件里写的，不是微信返回的

**Comment by ss7247** [comment]
@yorkie  解决了，真的是签名，我们之前的 android 签名用的别名是 “qq” , 心都碎了

**Comment by yorkie** [comment]
好 那我先关闭了～
