### ISSUE TITLE
ios  集成报错如下

### ISSUE THREAD

**Issue by ldzdz** [yorkie/react-native-wechat#234]
No visible @interface for 'RCTImageLoader' declares the selector 'loadImageWithURLRequest:size:scale:clipped:resizeMode:progressBlock:partialLoadBlock:completionBlock:'
应该怎么解决啊

**Comment by ldzdz** [comment]
@yorkie 
![image](https://user-images.githubusercontent.com/24790010/27675737-bda233da-5cdd-11e7-8765-cf8b489d5c78.png)

**Comment by ldzdz** [comment]
是不是问题过于简单，原生不是很会。。。。不吝赐教

**Comment by ldzdz** [comment]
: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/lib/libz.tbd (No such file or directory)

**Comment by yorkie** [comment]
你的React-Native多少版本，确认下是否是0.35以上 :)

**Comment by ldzdz** [comment]
我有两个工程，rn 都是0.34  但是一个集成完是好的，另一个就说没有libz.tbd。我看了下确实没有，应该怎么解决。另一个集成完无报错，功能也正常。

**Comment by ldzdz** [comment]
@yorkie  我有两个工程，rn都是0.34但是一个集成完成是好的，另一个就说没有libz.tbd。我看了下确实没有，应该怎么解决。另一个集成完无报错，功能也正常。

**Comment by yorkie** [comment]
那就在 XCode 里添加这个库就好了～

**Comment by ldzdz** [comment]
这个问题可以关闭了 0.34 也是支持的

**Comment by ldzdz** [comment]
谢谢作者
