### ISSUE TITLE
分享图片给朋友时，对方看不到缩略图

### ISSUE THREAD

**Issue by jumperChuck** [yorkie/react-native-wechat#241]
WeChat.shareToSession({
        type:'imageFile',
        title:'分享图片',
        imageUrl: 'file://'+uri,
        messageAction: undefined,
        messageExt: undefined,
        description: '账单',
    })
    .catch((error) => {
        alert(error.message);
    })

![wtf](https://user-images.githubusercontent.com/24954323/28003757-936bcaf2-6572-11e7-895c-58fad14ad42f.png)

**Comment by yorkie** [comment]
缺少`thumbImage`字段：https://github.com/yorkie/react-native-wechat#sharetotimelinedata
