### ISSUE TITLE
安卓微信登录和微信支付在取消时会闪退

### ISSUE THREAD

**Issue by JoeyCurry** [yorkie/react-native-wechat#246]
安卓微信登录和微信支付在取消时会闪退，正常支付或确认登录都没有问题。rn的版本时0.41,组件的版本是1.9.4

**Comment by JoeyCurry** [comment]
![image](https://user-images.githubusercontent.com/16148621/28155507-a3ed9542-67e1-11e7-84c4-dde75f75d3fd.png)
这是报错信息

**Comment by yorkie** [comment]
这个是1.9.4里面的已知Bug，切换到1.9.5试试

**Comment by JoeyCurry** [comment]
@yorkie 嗯 更新到最新到1.9.9就好了

**Comment by yorkie** [comment]
:) 关了～
