### ISSUE TITLE
react-native/React/Base/RCTBridgeModule.h:55:11: Duplicate protocol definition of 'RCTBridgeModule' is ignored

### ISSUE THREAD

**Issue by huchuanhui** [yorkie/react-native-wechat#247]
node_modules/react-native/React/Base/RCTBridgeModule.h:55:11: Duplicate protocol definition of 'RCTBridgeModule' is ignored

node_modules/react-native/React/Modules/RCTEventEmitter.h:16:1: Duplicate interface definition for class 'RCTEventEmitter'

    "react": "^16.0.0-alpha.6",
    "react-native": "^0.44.2",

**Comment by yorkie** [comment]
This seems to be an issue of React? And would you please upgrade your version latest, the 1.9.8 had a duplication error, too.

**Comment by huchuanhui** [comment]
您好 必须要升级到0.46吗？目前工程牵扯到一些 其他  不能直接升级到最新；

**Comment by huchuanhui** [comment]
https://user-images.githubusercontent.com/8064152/28410998-fe6a0d9e-6d71-11e7-9ed3-068d614a58b7.png

**Comment by yorkie** [comment]
现在的版本是多少～？

**Comment by huchuanhui** [comment]
"react": "^16.0.0-alpha.6",
"react-native": "^0.44.2",

**Comment by huchuanhui** [comment]
#import <React/RCTLinkingManager.h>
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}

不加以上代码  分享是能调用的 只不过 接受不到回调  不知道分享成功还是取消

**Comment by huchuanhui** [comment]
而且我昨天升级到0.46了 还是报同样的错    我也加入了友盟的推送、统计
![Uploading QQ20170721-105338@2x.png…]()

**Comment by huchuanhui** [comment]
而且我昨天升级到0.46了 还是报同样的错 我也加入了友盟的推送、统计
![image](https://user-images.githubusercontent.com/8064152/28447393-0d43f780-6e03-11e7-9279-c5df0023e0f8.png)

**Comment by huchuanhui** [comment]
ios版 shareToTimeline分享后的promise的事件监听、回调都没有   直接运行的 需要relaese打包吗

 wechat.shareToSession({
                title: '微信好友测试链接',
                description: '分享自:江清清的技术专栏(www.lcode.org)',
                thumbImage: 'http://mta.zttit.com:8080/images/ZTT_1404756641470_image.jpg',
                type: 'news',
                webpageUrl: 'http://www.lcode.org'
            }).then((result) => {
               console.log('wechatresult' + result)

           }).catch((error) => {
                alertShort(error.message);
            });
            // let result = await
            // console.log('result',result);

            wechat.once(
                'SendMessageToWX.Resp',
                (response) => {
                    console.log('wechat' + response)
                    if (parseInt(response.errCode) === 0) {
                        alertShort('分享成功');
                    }else  if (parseInt(response.errCode) === -2) {
                        alertShort('取消分享');
                    }else {
                        let message = response.errStr || response.errCode.toString();
                        alertShort(message);
                    }
                }
            );

**Comment by huchuanhui** [comment]
/Users/kokawaki/Documents/React-native/niurenRN/src/node_modules/react-native/React/Base/RCTBridgeModule.h:55:11: Duplicate protocol definition of 'RCTBridgeModule' is ignored
/Users/kokawaki/Documents/React-native/niurenRN/src/ios/huiniulicai/AppDelegate.m:15:9: In file included from /Users/kokawaki/Documents/React-native/niurenRN/src/ios/huiniulicai/AppDelegate.m:15:
/Users/kokawaki/Documents/React-native/niurenRN/src/node_modules/react-native-umeng-push/ios/RCTUmengPush/RCTUmengPush.h:11:9: In file included from ../node_modules/react-native-umeng-push/ios/RCTUmengPush/RCTUmengPush.h:11:
/Users/kokawaki/Documents/React-native/niurenRN/src/node_modules/react-native/React/Base/RCTBridgeModule.h:55:11: Previous definition is here
/Users/kokawaki/Documents/React-native/niurenRN/src/node_modules/react-native/React/Modules/RCTEventEmitter.h:16:1: Duplicate interface definition for class 'RCTEventEmitter'
/Users/kokawaki/Documents/React-native/niurenRN/src/ios/huiniulicai/AppDelegate.m:17:9: In file included from /Users/kokawaki/Documents/React-native/niurenRN/src/ios/huiniulicai/AppDelegate.m:17:
/Users/kokawaki/Documents/React-native/niurenRN/src/node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.h:12:9: In file included from ../node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.h:12:
/Users/kokawaki/Documents/React-native/niurenRN/src/node_modules/react-native/React/Modules/RCTEventEmitter.h:16:12: Previous definition is here
/Users/kokawaki/Documents/React-native/niurenRN/src/node_modules/react-native/React/Modules/RCTEventEmitter.h:18:40: Property has a previous declaration
/Users/kokawaki/Documents/React-native/niurenRN/src/ios/huiniulicai/AppDelegate.m:17:9: In file included from /Users/kokawaki/Documents/React-native/niurenRN/src/ios/huiniulicai/AppDelegate.m:17:
/Users/kokawaki/Documents/React-native/niurenRN/src/node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.h:12:9: In file included from ../node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.h:12:
/Users/kokawaki/Documents/React-native/niurenRN/src/node_modules/react-native/React/Modules/RCTEventEmitter.h:18:40: Property declared here

**Comment by yorkie** [comment]
> 不加以上代码 分享是能调用的 只不过 接受不到回调 不知道分享成功还是取消

这部分代码跟友盟是在同一个文件`AppDelegate.m`里吗？

**Comment by huchuanhui** [comment]
嗯 是的

**Comment by huchuanhui** [comment]
![image](https://user-images.githubusercontent.com/8064152/28465270-b3345fe8-6e5a-11e7-9ea9-8da463ce9c4d.png)

**Comment by huchuanhui** [comment]
改了友盟推送的写法  #import <React/RCTBridgeModule.h>  目前只剩上面2个错了

**Comment by yorkie** [comment]
剩下的两个问题都是 niurenRN 的问题了，这个是第三方库吗？我貌似没在 GitHub 上搜到呢～

**Comment by huchuanhui** [comment]
这是rn  源码吧  In file included from ../node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.h:12:

**Comment by yorkie** [comment]
错误的意思是 niurenRN 内部的代码跟 React-Native 源码中的定义冲突了，所以还是 niurenRN 的问题的。

**Comment by huchuanhui** [comment]
#import <React/RCTEventEmitter.h>
意思要保持这种写法是吧
    "react-native-umeng-push": "git+https://github.com/chinaczy/react-native-umeng-push.git",
用的是这个

**Comment by yorkie** [comment]
这个跟友盟没有关系了吧？

**Comment by huchuanhui** [comment]
嗯 对 也是对友盟的封装

#import "RCTLinkingManager.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  
  return [RCTLinkingManager application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
  
}

是不是不加这些代码  iOS 分享就拿不到回调

**Comment by yorkie** [comment]
可以把 `#import "RCTLinkingManager.h"`去掉

**Comment by huchuanhui** [comment]
但是 下面的  [RCTLinkingManager  就编译不通过了

**Comment by yorkie** [comment]
有完整的 AppDelegate.m 代码吗？

**Comment by huchuanhui** [comment]
嗯 
#import "AppDelegate.h"
#import <AVFoundation/AVFoundation.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "SplashScreen.h"
#import "RCTUmengPush.h"
#import <UMMobClick/MobClick.h>
#import "RCTLinkingManager.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  
  return [RCTLinkingManager application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
  
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  UMConfigInstance.appKey = @"";
  NSString *version = [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleShortVersionString"];
  [MobClick setAppVersion:version];
  [MobClick startWithConfigure:UMConfigInstance];//配置以上参数后调用此方法初始化SDK！
  [MobClick setLogEnabled:YES];
  
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@""
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
  [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil]; 
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [SplashScreen show];
  
  //注册友盟推送
  [RCTUmengPush registerWithAppkey:@"" launchOptions:launchOptions];
  return YES;
}


- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  //获取deviceToken
    [RCTUmengPush application:application didRegisterDeviceToken:deviceToken];
}


- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
{
  //获取远程推送消息
  [RCTUmengPush application:application didReceiveRemoteNotification:userInfo];
}





@end

**Comment by yorkie** [comment]
嗯 然后把：

```objc
#import "RCTLinkingManager.h"
```

改成：

```objc
#import <React/RCTBridgeModule.h>
```

**Comment by huchuanhui** [comment]
![image](https://user-images.githubusercontent.com/8064152/28474608-e7600436-6e7b-11e7-8bd3-0fe549686161.png)好 我试试

**Comment by huchuanhui** [comment]
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  
  return [RCTLinkingManager application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
  
}
那下面的  RCTLinkingManager也换掉是吧？

**Comment by yorkie** [comment]
不对，应该换成：`<React/RCTLinkingManager.h>`

**Comment by huchuanhui** [comment]
嗯 这个 我也试过了  
/Users/kokawaki/Documents/React-native/niurenRN/src/node_modules/react-native/React/Modules/RCTEventEmitter.h:16:1: Duplicate interface definition for class 'RCTEventEmitter'
/Users/kokawaki/Documents/React-native/niurenRN/src/ios/。。。/AppDelegate.m:17:9: In file included from /Users/kokawaki/Documents/React-native/niurenRN/src/ios/huiniulicai/AppDelegate.m:17:
/Users/kokawaki/Documents/React-native/niurenRN/src/node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.h:12:9: In file included from /Users/kokawaki/Library/Developer/Xcode/DerivedData/。。-cbbwnjmnpapizhdiozwrtqwqhkoq/Build/Products/Debug-iphoneos/include/React/RCTLinkingManager.h:12:
/Users/kokawaki/Documents/React-native/niurenRN/src/node_modules/react-native/React/Modules/RCTEventEmitter.h:16:12: Previous definition is here
/Users/kokawaki/Documents/React-native/niurenRN/src/node_modules/react-native/React/Modules/RCTEventEmitter.h:18:40: Property has a previous declaration
/Users/kokawaki/Documents/React-native/niurenRN/src/ios/。。。/AppDelegate.m:17:9: In file included from /Users/kokawaki/Documents/React-native/niurenRN/src/ios/huiniulicai/AppDelegate.m:17:
/Users/kokawaki/Documents/React-native/niurenRN/src/node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.h:12:9: In file included from /Users/kokawaki/Library/Developer/Xcode/DerivedData/。。。-cbbwnjmnpapizhdiozwrtqwqhkoq/Build/Products/Debug-iphoneos/include/React/RCTLinkingManager.h:12:

**Comment by huchuanhui** [comment]
好像 RCTLinkingManager的路径 就指引错了  这时候我是不是要去掉
![image](https://user-images.githubusercontent.com/8064152/28474910-f0063348-6e7c-11e7-807d-9ad31aa82076.png)

**Comment by huchuanhui** [comment]
![image](https://user-images.githubusercontent.com/8064152/28474967-27900b36-6e7d-11e7-8c70-9ee503006ae1.png)

**Comment by huchuanhui** [comment]
hi  上午我测试了 注释掉 集成友盟推送的代码后 就编译运行通过了
您是否帮忙看下  2者的写法是不是不一样 我可以回退到哪个 版本的wechat 就行了
"react-native-umeng-push": "git+https://github.com/chinaczy/react-native-umeng-push.git",

**Comment by huchuanhui** [comment]
已解决  修改 "react-native-umeng-push

中   RCTUmengPush.h中以下代码
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>
