### ISSUE TITLE
支付操作完成，如何给用户支付结果提示，errCode貌似不起作用

### ISSUE THREAD

**Issue by tiantian520** [yorkie/react-native-wechat#251]
支付操作完成后，想给用户提示支付结果，试了两种方式：
1.直接对pay方法返回的promise对象，取errCode判断，如下：
![image](https://user-images.githubusercontent.com/13825897/28562208-f3030344-7153-11e7-8bde-4726c37257e2.png)
2.监听WeChat_Resp事件（或者PayReq.Resp），判断errCode，如下：
![image](https://user-images.githubusercontent.com/13825897/28562429-be81aa48-7154-11e7-9863-230b1d44d909.png)
但都没有用。菜鸟求指导！

**Comment by yorkie** [comment]
你不需要手动监听 WeChat_Resp 事件，直接捕捉异常就好了，所以这个问题在于你是怎么确定你的操作出错的？

**Comment by tiantian520** [comment]
捕捉异常并没有作用，依然不会弹窗提醒

![image](https://user-images.githubusercontent.com/13825897/28565268-49b6f22c-715e-11e7-8cbe-83f5b93fe842.png)

**Comment by yorkie** [comment]
我的意思是什么错误？

**Comment by tiantian520** [comment]
比如：我点击支付按钮，跳到支付界面，不支付直接点击返回（即用户“取消支付”），这时候并不会捕捉到“取消支付”这个异常，从而不能给用户提示信息。（代码如上一张图所示）

**Comment by tiantian520** [comment]
没问题了，因为别的原因。谢谢作者答复。

**Comment by nickychenqin** [comment]
您好，我这边也收不到返回值 @tiantian520 @yorkie   您是什么原因呢
wechat.pay调用后，没有拿到返回结果，捕捉异常也没有走？
代码如下：
goPay=async()=>{
let wxPayData = this.state.wxPayData;
let isInstalled = wechat.isWXAppInstalled();
if(isInstalled){
await wechat.pay(
{
partnerId: wxPayData.partnerId, // 商家向财付通申请的商家id
prepayId: wxPayData.prepayId, // 预支付订单
nonceStr: wxPayData.nonceStr, // 随机串，防重发
timeStamp:wxPayData.timeStamp, // 时间戳，防重发
package: wxPayData.package, // 商家根据财付通文档填写的数据和签名
sign: wxPayData.sign,// 商家根据微信开放平台文档对数据做的签名
extData:"app data"
}
).then((success)=>{
alert(success); //没有走
}).catch((error)=>{
alert(error); //没有走
});
}else {
alert('没有安装微信软件，请您安装微信之后再试');
}
}
