### ISSUE TITLE
Error: more than one library with package name 'com.theweflex.react'

### ISSUE THREAD

**Issue by 7caishi** [yorkie/react-native-wechat#258]
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Error: more than one library with package name 'com.theweflex.react'

请问这个是什么问题，大牛指点一下

**Comment by 7caishi** [comment]
已经解决
https://github.com/yorkie/react-native-wechat/issues/225#issuecomment-309327967

**Comment by 7caishi** [comment]
build.gradle 里面 不应该是 :RCTWeChat 这个，应该是compile project(':react-native-wechat')

**Comment by jasonzhangdong** [comment]
你那样做不会有错？我和你报同样的错误，但是改为找不到符号
    protected List<ReactPackage> getPackages()，android报错找不到符号
    protected List<ReactPackage> getPackages() {
              ^
  符号:   类 List
  位置: 类 MainActivity
