### ISSUE TITLE
按照步骤安装配置后，出现“undefined is not an object(evaluating 'WeChat.registerApp')”

### ISSUE THREAD

**Issue by MinzhangWei** [yorkie/react-native-wechat#261]
![image](https://user-images.githubusercontent.com/4898303/28868380-e307b044-77ab-11e7-8ef1-3ef6e74742d5.png)

然后我在源码里头找到

````
import { DeviceEventEmitter, NativeModules } from 'react-native';
import { EventEmitter } from 'events';

let isAppRegistered = false;
const { WeChat } = NativeModules;
````

这个 `WeChat` 是空的，是什么问题导致的呢？

**Comment by chenqi777** [comment]
我回退到了旧版本解决了这个问题.  yarn add react-native-wechat@1.9.2

**Comment by MinzhangWei** [comment]
@chenqi777 这是xcode没有添加相应的lib导致的。大家遇到这个问题可以检查一下lib是否添加成功。

**Comment by dioxide** [comment]
RN 0.47.1 似乎link有点问题，  需要手动链接下 libRCTWeChat.a

**Comment by yorkie** [comment]
先关掉了～属于操作问题
