### ISSUE TITLE
Xcode: Apple Mach-O Linger Error

### ISSUE THREAD

**Issue by zzzeee** [yorkie/react-native-wechat#265]
按照文档配置IOS， 报错：
<img width="731" alt="2017-08-07 4 53 41" src="https://user-images.githubusercontent.com/26219025/29019514-4f3656ec-7b91-11e7-80ff-8c7b4d1ff513.png">
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Xcode: 8.3
react native : 0.44.3
react-native-wechat: 1.9.9

**Comment by jiangbo2015** [comment]
同求，也是报这个错误

**Comment by jiangbo2015** [comment]
我试了，去掉文档中写的这段代码，运行OK，
```
#import "RCTLinkingManager.h"

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                            sourceApplication:sourceApplication annotation:annotation];
}
```

**Comment by zzzeee** [comment]
这应该是回调， 如果去掉这个函数，就无法触发回调了。

**Comment by jiangbo2015** [comment]
已经搞定了，不能使用react-native link ,要手动link完了以后，按照步骤是没有问题的，
