### ISSUE TITLE
Android 微信取消分享后，App闪退

### ISSUE THREAD

**Issue by CodingMonkeyzh** [yorkie/react-native-wechat#266]
使用的版本为 `"react-native-wechat": "^1.9.9",`
env: 
- `"react-native": "0.46.3",`
- `Android 7.0`

按照文档配置好后，打包App进行测试，发现微信登录工作正常；微信分享，如果成功分享，可以正常返回App，但是如果“取消”了分享操作，返回App后，App立马闪退。抓取到到 log 如下：

![image](https://user-images.githubusercontent.com/2787386/29278678-0c359134-8148-11e7-80eb-bae238574f34.png)

请问，可能是哪里出了问题？谢谢

**Comment by CodingMonkeyzh** [comment]
`new WeChatPackage()` 放在了 `MainApplication` 下：
![image](https://user-images.githubusercontent.com/2787386/29279100-57e6339e-8149-11e7-8f73-28e797b2fada.png)

**Comment by ftao123** [comment]
也遇到同样问题

**Comment by HancleLee** [comment]
我在安装 “npm install react-native-wechat --save”之后，执行“react-native link react-native-wechat”，然后再配置，解决了这个问题，你可以试试!

**Comment by CodingMonkeyzh** [comment]
@HancleLee 重新安装，link 之后再配置依然存在这个问题

**Comment by yoyo0427** [comment]
遇到同样的问题

**Comment by saigyouyou** [comment]
我也遇到了同样的问题。
1.9.9版本一样会在分享取消的时候闪退，重启app
当时做这个功能的时候取消会返回-2，但是现在不行了，因此怀疑是跟某些库有冲突，也许是极光推送的sdk？

**Comment by CodingMonkeyzh** [comment]
> 原因是换了包名之后wxapi里的包名忘了换

@saigyouyou 请问你指的是 `WXEntryActivity` 这个类下的包名吗？

**Comment by saigyouyou** [comment]
@CodingMonkeyzh 是的，我更改过一次包名，所以出现了这个问题。WXEntryActivity最上面的包名和路径不一致了。

WXEntryActivity 就是用来解决取消时候回调调不到页面闪退的问题的，你看看是不是没有写对应的调用activity的方法。

**Comment by yoyo0427** [comment]
@CodingMonkeyzh 请问一下这个问题解决了吗？

**Comment by CodingMonkeyzh** [comment]
@yoyo0427 微信更新到 7.0 之后，没有这个问题了
