### ISSUE TITLE
和UM share 引用资源重复

### ISSUE THREAD

**Issue by dongodngtang** [yorkie/react-native-wechat#271]
duplicate symbol _OBJC_IVAR_$_WXOMTAStore.db in:
    /Users/lorne/MyGit/PokerPro/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(MTAStore.o)
    /Users/lorne/MyGit/PokerPro/ios/build/Build/Products/Debug-iphonesimulator/libRCTUMShareModule.a(MTAStore.o)
duplicate symbol _OBJC_IVAR_$_WXOMTADataConfig._md5 in:
    /Users/lorne/MyGit/PokerPro/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(MTAStore.o)
    /Users/lorne/MyGit/PokerPro/ios/build/Build/Products/Debug-iphonesimulator/libRCTUMShareModule.a(MTAStore.o)
duplicate symbol _OBJC_CLASS_$_WXOMTAOpenUDID in:
    /Users/lorne/MyGit/PokerPro/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(OpenUDID.o)
    /Users/lorne/MyGit/PokerPro/ios/build/Build/Products/Debug-iphonesimulator/libRCTUMShareModule.a(OpenUDID.o)
duplicate symbol _OBJC_METACLASS_$_WXOMTAOpenUDID in:
    /Users/lorne/MyGit/PokerPro/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(OpenUDID.o)
    /Users/lorne/MyGit/PokerPro/ios/build/Build/Products/Debug-iphonesimulator/libRCTUMShareModule.a(OpenUDID.o)
ld: 440 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yorkie** [comment]
移除掉多余的依赖项就可以了～
