### ISSUE TITLE
IOS:undefined is not an object (evaluating ‘WeChat.registerApp’)

### ISSUE THREAD

**Issue by t407289575** [yorkie/react-native-wechat#272]
自动Link后，安卓能运行
IOS 执行 import * as WeChat from 'react-native-wechat'; 后就报错：
undefined is not an object (evaluating ‘WeChat.registerApp’)

**Comment by t407289575** [comment]
已解决：ios通过手动link能解决问题 参考：http://www.jianshu.com/p/3f424cccb888

**Comment by yorkie** [comment]
好 那我关了～

**Comment by 2639949627** [comment]
我按照官方的手动link，依然无法解决。

**Comment by 349989153** [comment]
@t407289575 根据简书手动link成功了，多谢

@yorkie 个人觉得不应该关闭这个issue，应该把这个issue打开，关闭其他相同的。因为那些issue里面，要么没有解决方案，要么说了手动link但是没说怎么手动link。开着这个，就会方便后面遇到这个问题的人，解决问题。

**Comment by AisonBird** [comment]
这个问题这么久依然没有修复。。。

**Comment by afh19840516** [comment]
libcxxreact.a
libjschelpers.a
libReact.a
libyoga.a

libRCTWeChat.a
都要手动添加

**Comment by hms111111** [comment]
0.59,安卓模拟器自动link还是报错null is not an object (evaluating 'WeChat.registerApp')
