### ISSUE TITLE
isWXAppInstalled在render中判断显示。

### ISSUE THREAD

**Issue by byk04712** [yorkie/react-native-wechat#274]
需求是我在 `render` 函数中调用`isWXAppInstalled`来判断用户手机上是否安装微信，如果安装了显示微信登录方式，如果没安装则不显示，但是由于调用 `Wechat.isWXAppInstalled()` 返回是一个 Promise 对象，现在请求各位大神支支招，给点思路，我这应该怎么写，只要我在 render 中能根据是否安装微信显示不同的内容就行。

**Comment by yorkie** [comment]
render() 一般是用来做渲染用的，所有异步的数据请求都应该放在 componentDidMount/componentWillMount 做～
