### ISSUE TITLE
安卓和IOS分享给好友后，选择“留在微信”，则不能触发回调？

### ISSUE THREAD

**Issue by whyming** [yorkie/react-native-wechat#276]
```
async function shareToWechat(url) {
  try {
    const wechatResult = await shareToSession({
      title:"xxxxx",
      description: "xxxxxxxx",
      thumbImage: "https://www.xxxx.com/logo.jpg",
      type: "news",
      webpageUrl: url
    })
    alert(1) //这里执行不到
  } catch (e) {
    alert(2) //这里执行不到
  } finally {
    alert(3) //这里执行不到
  }
}
```

代码如上
首先，正常操作流程可正常触发回调，正常流程是：触发shareToSession，->微信打开后选在好友，->分享后选择返回APP ->回调正常。
但是如果在最后一步选择“留在微信”，然后再切换回APP则一直处于等待，不能触发回调，也没有异常抛出。这个现象在安卓和IOS上一致。
另外还有一个不一致的现象，触发shareToSession->微信打开后,返回APP，在安卓上可以用back键返回APP也可以用左上角的箭头，能够正常触发异常，可以捕捉到。但是IOS上，通过状态栏的小字，点击返回到APP，不触发任何回调和异常。

请问，当前版本设计如此，还是说我的配置有问题，如果是我配置有问题，可否提供一个检查思路？已经按照README的说明检查两遍了，没有问题，而且正常使用也OK。

**Comment by yorkie** [comment]
代码没有问题，多半这种问题还是应用签名问题，请仔细检查下～

**Comment by jonjia** [comment]
但是如果在最后一步选择“留在微信”，然后再切换回APP则一直处于等待，不能触发回调，也没有异常抛出。这个现象在安卓和IOS上一致。

也是遇到这个问题， @whyming @yorkie 有解决吗?
