### ISSUE TITLE
undefined is not an object(evaluating 'WeChat.registerApp')

### ISSUE THREAD

**Issue by luyuan11233** [yorkie/react-native-wechat#281]
when I use react-native-wechat in my project,I get this error.I use react-native in 0.47,this is the error picture...how to solve this issue?
![1504579714970](https://user-images.githubusercontent.com/15043392/30043053-e6708abc-9227-11e7-8787-7aa397121d9f.jpg)

**Comment by luyuan11233** [comment]
I follow the Build for iOS, but it doesn't work too

**Comment by wulala** [comment]
补充一句， Android没毛病

**Comment by wangxiongxp** [comment]
me to

**Comment by lhh-sofy** [comment]
自动link文件或许不全，需要手动link。

**Comment by hiling** [comment]
me to

**Comment by luyuan11233** [comment]
确实，手动link后就好了、、、避免更多的人入坑，建议修复下这个问题、、、

**Comment by luyuan11233** [comment]
感谢大家的热心帮助

**Comment by Jimi6** [comment]
@luyuan11233    弱弱问一句，怎么手动link

**Comment by HHuiHao** [comment]
@Jimi6 试试： react-native link react-native-wechat

**Comment by HHuiHao** [comment]
@Jimi6 `react-native link react-native-wechat`

**Comment by luyuan11233** [comment]
@Jimi6  你打开react-native-wechat 有几种把包放进项目的方式，你选那个直接拖拽包到相关目录的方式，然后在添加以来，就是手动link了

**Comment by yangdachu** [comment]
@luyuan11233 能具体说一下吗
