### ISSUE TITLE
调用wechat.pay方法，返回Promise {_40: 0, _65: 0, _55: null, _72: null}

### ISSUE THREAD

**Issue by 2415621370** [yorkie/react-native-wechat#283]
wxpay=()=> {
    try {
      let result = wechat.pay({
        "partnerId": wx.partnerId,
        "prepayId": wx.prepayId,
        "timeStamp": "1504082881920",
        "sign": "021A312EBAB772ED2649433FF85D86BF",
        "nonceStr": "f8yndYD92vB0Jnx46WU0NNIUCNfo0npe",
        "package": "Sign=WXPay"
      });

      console.log(result)
    } catch (error) {
      console.log(error)
    }
  }

result 返回Promise {_40: 0, _65: 0, _55: null, _72: null}，这是哪里错误导致得呢？

**Comment by yorkie** [comment]
没有错 你少加了 `await`

**Comment by 2415621370** [comment]
![aa11](https://user-images.githubusercontent.com/19277482/30261842-053ad00a-9701-11e7-8e22-be8279f00a6f.png)
![bb39](https://user-images.githubusercontent.com/19277482/30261855-0f442b0a-9701-11e7-80ba-2cfc9c5ac26b.png)


还是有问题

**Comment by yorkie** [comment]
什么问题？

**Comment by 2415621370** [comment]
https://user-images.githubusercontent.com/19277482/30261842-053ad00a-9701-11e7-8e22-be8279f00a6f.png
https://user-images.githubusercontent.com/19277482/30261855-0f442b0a-9701-11e7-80ba-2cfc9c5ac26b.png

方法加上了 await，但是不输出结果，看到react-native-wechat ，index.js result 输出为null.界面没有任何变化呢，还请大神请教。

**Comment by luoyechen** [comment]
@2415621370 我也遇到了，请问你解决这个问题了么
