### ISSUE TITLE
微信登录成功调起微信，点击确认登录后返回APP，但是没有返回值

### ISSUE THREAD

**Issue by githuchunyu** [yorkie/react-native-wechat#285]
then，catch，done都没有执行，是不是没有监听到返回？

**Comment by githuchunyu** [comment]
`DeviceEventEmitter.addListener('WeChat_Resp', resp => {
  console.log('bbb'); //没有被执行
  emitter.emit(resp.type, resp);
});`

**Comment by rabbitzbx** [comment]
hi~我遇到了同样的问题，请问你是怎样解决的？
