### ISSUE TITLE
WeChat.pay 返回 WeChat API invoke returns false 

### ISSUE THREAD

**Issue by 447491480** [yorkie/react-native-wechat#288]
如标题所示，调用支付接口 catch到了异常信息。
调用isWXAppInstalled 是正常的。

android 4.4.3
react-native: 0.48.3

**Comment by 447491480** [comment]
这个问题是签名问题，已经解决了

**Comment by DonChengCheng** [comment]
我也遇到相同的问题，你是怎么解决的，能详细说一下吗？
