### ISSUE TITLE
安卓点击分享没反应，iOS是正常的

### ISSUE THREAD

**Issue by isennn** [yorkie/react-native-wechat#293]
前两天接的，第一次接的时候是微信应用签名没配置对，出现的情况是点击分享闪出一下然后又返回来了，之后把微信的应用签名配好之后，测过之后可以分享的。但是过了两天之后再次测分享的时候，点击分享没有反应了，连第一次那种现象都没有了，打了log,share的方法都已经执行了，但是就是没反应。然后整个配置流程都检查了一遍都是ok的。。求解

**Comment by isennn** [comment]
问题已经解决了，我们现在是分享图片，但是shareToSession里面的有个thumbImage，这个字段只能在ios平台使用，如果不区分平台的话，就会出现我之前上面那个问题，点击分享是没有反应的。给后面的朋友做个提示。。

**Comment by godot007** [comment]
作者没做thumbImage图片不能大于32k的处理。期待作者能够完善
