### ISSUE TITLE
WeChat.sendAuthRequest 没有任何反应

### ISSUE THREAD

**Issue by Vinkugor** [yorkie/react-native-wechat#295]
let scope = 'snsapi_userinfo';
	let state = 'wechat_sdk_demo';
	WeChat.isWXAppInstalled()
    .then(isInstalled => {
		if(isInstalled){
			console.log("有安装微信")
			WeChat.sendAuthRequest(scope)
			.then(responseCode => {
				console.log(responseCode)
				//返回code码，通过code获取access_token
				alert(responseCode.code);
			})
			.catch(err => {
				console.log(err)
				alert('登录授权发生错误：', err.message);
			})
		}else{
			alert('没有安装微信')
		}
只打印出"有安装微信",之后没有任何反应了.........

**Comment by Vinkugor** [comment]
registerApp返回true
 getApiVersion和openWXApp都没问题.
sendAuthRequest、shareToSession和shareToTimeline就不行
shareToSession和shareToTimeline只是闪动了一下，转了半秒菊花，然后就没然后了。
有大神救赎一下吗

**Comment by Vinkugor** [comment]
问题解决了，是由于包名和签名问题，需要在微信开发平台上设置的。

**Comment by yangslgithub** [comment]
至少说下怎么设置吧...

**Comment by LiDevil** [comment]
duplicate #346
