### ISSUE TITLE
请问这个库还有在维护吗,issues里的坑遇到了几个,但是答案没有一个起效果,RN:0.5.1

### ISSUE THREAD

**Issue by etouyang** [yorkie/react-native-wechat#319]

**Comment by jiw0220** [comment]
我ios用这个库,已经接了好几个项目了没什么问题.你说说看呢

**Comment by etouyang** [comment]
ios测试:
1.自动link,无效;
2.手动link, library not found for -lWeChatSDK,在library search path里面添加了$(SRCROOT)/../node_modules/react-native-wechat/ios,继续...
3.js端提示react-native Application XXX has not been registered.然后在header里面添加$(SRCROOT)/../node_modules/react-native/Libraries  $(SRCROOT)/../node_modules/react-native/React, 继续...
4.js端引用(issue里面提及的各种引用都试过了), 报错:undefined is not an object (evaluating ‘WeChat.registerApp’) ...

**Comment by etouyang** [comment]
const { WeChat } = NativeModules;
这个WeChat是空, js通信找不到本地模块,请问你有什么好的建议

**Comment by Tennen** [comment]
是不是你的project就有问题呢, 要不就发个demo出来看看, 光这样说别人也不知道怎么回事的.

**Comment by yorkie** [comment]
库还在维护，什么问题～？

**Comment by qwlong** [comment]
ios测试:
1.自动link,无效;
我也碰到了这个问题

**Comment by qwlong** [comment]
@etouyang 你解决这个问题了吗？

**Comment by etouyang** [comment]
参考网上的教程, 我自己写了Android,ios微信支付宝源码,js封装了一下,然后调用

**Comment by giantss** [comment]
@etouyang 我的问题跟你一样 请问是怎么解决的

**Comment by giantss** [comment]
@etouyang 谢谢，我的问题已经解决了原因是导入组件的时候写错了
我的错误写法是： `import  WeChat from 'react-native-wechat'`
应该是：`import * as WeChat from 'react-native-wechat'`
