### ISSUE TITLE
现有版本SDK不支持分享小程序，能尽快更新SDK么

### ISSUE THREAD

**Issue by jeffy7** [yorkie/react-native-wechat#325]

**Comment by qqqzhch** [comment]
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419317340&token=&lang=zh_CN
这个功能的确不错 分享支持微信小程序

**Comment by qqqzhch** [comment]
我计划在 合格sdk基础上怎家分享微信小程序的功能但是 我现在的项目还没有小程序
楼上的项目里面有小程序 能测试这个分享吗？

**Comment by jeffy7** [comment]
我没有用作者的这个，是自己拖的，至于测试，你得看微信开放平台有没有提供测试数据，作者如果更新了最新的SDK，这个功能应该不会有问题。

**Comment by JohnSmith0602** [comment]
目前使用这个库也碰到了分享小程序的需求，请问下有计划大概什么时候会支持吗？谢谢～

**Comment by qqqzhch** [comment]
原来ios 库文件已经封装好了  其他人修改不了
什么时候支持分享小程序呢

**Comment by allenxieyusheng** [comment]
谁能改下这个裤不？？？？？

**Comment by yutianhaijiao** [comment]
在这个基础上，自己维护吧
