### ISSUE TITLE
调用sendAuthRequest接口，点击确认登录无反应

### ISSUE THREAD

**Issue by Kennytian** [yorkie/react-native-wechat#329]
"react native: 0.52.0",
"react-native-wechat": "^1.9.9",

iPhone版本：11.2.2，WeChat版本： 6.6.1

registerApp result 返回true。shareToSession和shareToTimeline都正常。

微信登录 | 使用微信帐号登录App或者网站 详情 | 已获得

使用sendAuthRequest接口，可以调起微信，但点击「确认登录」无反应。

调用方式：

const scope = 'snsapi_userinfo';
WeChat.sendAuthRequest(scope).then((result) => {
      console.log('微信登录信息：', result);
      alert(JSON.stringify(result));
});

和

const scope = 'snsapi_userinfo';
const result = await WeChat.sendAuthRequest(scope);

console.log('微信登录信息：', result);
alert(JSON.stringify(result));

上面两行代码在Debug和Release都没有消息。

**Comment by budiga** [comment]
+1,微信未登录状态下能调起，登录后却调不起，why？
`
"react-native": "0.50.4",
"react-native-wechat": "^1.9.9",

`
Android版本：5.1.1，华为荣耀和小米3是这个问题。

**Comment by summmmer** [comment]
现在有解决办法了吗

**Comment by qwlong** [comment]
@Kennytian @benaheng @summmmer 解决了吗？

**Comment by qwlong** [comment]
@yorkie 大神看看什么情况

**Comment by summmmer** [comment]
IOS有回掉，但是是自动授权，是微信服务器缓存？
Android只是闪了一下微信的页面，然后没有回掉，之前是因为签名不正确，改正后还是不行，难道需要重新生成签名？

**Comment by qwlong** [comment]
我这边解决了，是因为URL Types的问题，看看可以帮助你们不 @Kennytian 
![image](https://user-images.githubusercontent.com/607963/35719570-fd767b9a-0824-11e8-9c58-5537bcd56c72.png)

**Comment by Kennytian** [comment]
@yunuo-tech 
谢谢你，我当时也是用你的办法解决，后来忘了关这个issue了

**Comment by 1797918430** [comment]
UrlType 设置错了会跳不回来 Url Schemes那里用申请的appId
