### ISSUE TITLE
Android无法进入分享成功回调

### ISSUE THREAD

**Issue by chinachuner** [yorkie/react-native-wechat#339]
看了之前的一些Issues.
我测试了我的EntryActivity.java
没有走到super.onCreate(savedInstanceState);

我们项目中原来有个WXEntryActivity
所以我新建了一个WeChatEntryActivity.java
AndroidManifest.xml中配置了
< activity
                android:name=".wechat.WechatEntryActivity"
                android:label="@string/app_name"
                android:exported="true"
        />
分享的函数都能调用就是成功没有回调，可能是什么问题呢？

**Comment by wanxsb** [comment]
1.包名和签名，跟微信后台登记的不一样，导致无法调起微信
2.回调类WXEntryActivity 的包名和 application Id不一致，导致无法回调

**Comment by gdoudeng** [comment]
> 看了之前的一些问题。
> 我测试了我的EntryActivity.java 
> 没有走到super.onCreate（savedInstanceState）;
> 
> 我们项目中原来有个WXEntryActivity 
> 所以我新建了一个WeChatEntryActivity.java 
> AndroidManifest.xml中配置了
> <activity 
> android：name =“。wechat.WechatEntryActivity” 
> android：label =“@ string / app_name” 
> android：exported =“true” 
> /> 
> 分享的函数都能调用就是成功没有回调，可能是什么问题呢？

我也有个原本有个WXEntryActivity，请问您最后是怎么解决了呢？
