### ISSUE TITLE
安卓登录问题 : 已经注册好 , 但是一点登录就闪退app 求指教

### ISSUE THREAD

**Issue by BINAIMENG** [yorkie/react-native-wechat#373]
```
 WXLogin = (wx) => {
    let scope = 'snsapi_userinfo';
    //一调用登录就闪退
    wechat.sendAuthRequest(scope);
  };
  componentWillMount(){
  }
  componentDidMount() {
   ///appID是对的
    wechat.registerApp('xxxx');
  }
```

**Comment by Vi-jay** [comment]
+1

**Comment by Vi-jay** [comment]
已解决，重装微信

**Comment by sjq9026** [comment]
@BINAIMENG 怎么处理的 老铁

**Comment by BINAIMENG** [comment]
@sjq9026  
wechat.isWXAppInstalled()
      .then((isInstalled) => {
        if (isInstalled) {
          //发送授权请求
          wechat.sendAuthRequest(scope, state)
            .then(responseCode => { 
              //返回code码，通过code获取access_token
                getCode(responseCode)
              })
              .catch(err => {
                Alert.alert('登录授权发生错误：', err.message, [{
                  text: '确定'
                }]);
              })
        } else {
          Platform.OS == 'ios' ?
            Alert.alert('没有安装微信', '是否安装微信？', [
              {text: '取消'},
              {text: '确定', onPress: () => this.installWechat()}
            ]) :
            Alert.alert('没有安装微信', '请先安装微信客户端在进行登录', [
              {text: '确定'}
            ])
        }
      })

**Comment by vitozyf** [comment]
遇到了同样的问题，重装微信没用。请问解决了吗

**Comment by yaroslavnikiforov** [comment]
+1
