### ISSUE TITLE
无法监听分享失败回调

### ISSUE THREAD

**Issue by 1035901787** [yorkie/react-native-wechat#397]
环境： mac
版本：
"react": "16.3.1",
"react-native": "0.55.4",
"react-native-wechat": "^1.9.9",

问题：无法监听到分享失败回调，只能监听到成功回调，分享失败也会进入成功回调

预期：可以分别监听到成功和失败回调

**Comment by daxiangaikafei** [comment]
同上

**Comment by daxiangaikafei** [comment]
https://open.weixin.qq.com/cgi-bin/announce?action=getannouncement&key=11534138374cE6li&version=&lang=&token=
