### ISSUE TITLE
ios中isWXAppInstalled方法一直是false,求大神指教

### ISSUE THREAD

**Issue by qubangliuhui** [yorkie/react-native-wechat#401]
请个位大佬救急，前面同样问题的解答没看懂

**Comment by zeayal** [comment]
我按照这个 https://github.com/yorkie/react-native-wechat/blob/master/docs/build-setup-ios.md 设置了就好了

**Comment by aiynmm** [comment]
+1

**Comment by hu-qi** [comment]
> +1

请问您也是通过上边的设置就好了吗

**Comment by zeayal** [comment]
> > +1
> 
> 请问您也是通过上边的设置就好了吗

对啊 ，你试一下

**Comment by qubangliuhui** [comment]
不用这个库的isWXAppInstalled方法，用RN自己的Link去判断iOS的，Android的我没看

发自我的 iPhone
