### ISSUE TITLE
Error:(11, 17) 错误: 无法访问IWXAPIEventHandler 找不到com.tencent.mm.sdk.openapi.IWXAPIEventHandler的类文件

### ISSUE THREAD

**Issue by orzhtml** [yorkie/react-native-wechat#410]
Error:(11, 17) 错误: 无法访问IWXAPIEventHandler
找不到com.tencent.mm.sdk.openapi.IWXAPIEventHandler的类文件

**Comment by liuoomei** [comment]
> Error:(11, 17) 错误: 无法访问IWXAPIEventHandler
> 找不到com.tencent.mm.sdk.openapi.IWXAPIEventHandler的类文件

![image](https://user-images.githubusercontent.com/31230575/50625031-28f60680-0f60-11e9-9faf-97b7335a69de.png)
tong同求啊

**Comment by liuoomei** [comment]
解决了，修改 react-native-wechat 的gradlew的dependencies 下的implementation改为api
![image](https://user-images.githubusercontent.com/31230575/50626156-9b1e1980-0f67-11e9-83a7-7e0f0cc10d0e.png)

**Comment by liuoomei** [comment]
解决了，改 react-native-wechat的gradlew

**Comment by hms111111** [comment]
太谢谢了.头皮想炸了都想不出问题怎么解决!!!
