### ISSUE TITLE
IOS没问题，安卓打包后返回原应用会直接闪退

### ISSUE THREAD

**Issue by vitozyf** [yorkie/react-native-wechat#421]
查看了微信开放平台，和打包后的签名，是一致的。

"react": "16.5.0",
"react-native": "0.57.2",
"react-native-wechat": "^1.9.10",

**Comment by lwxzks** [comment]
我也是

**Comment by vitozyf** [comment]
> 我也是

我这边是因为在WXEntryActivity.java文件中代码问题

**Comment by cnpmge** [comment]
闪退咋解决的？
