### ISSUE TITLE
安卓手机分享后，返回app导致app闪退

### ISSUE THREAD

**Issue by orzhtml** [yorkie/react-native-wechat#434]
安卓手机分享后，返回app导致app闪退

**Comment by yoyo0427** [comment]
@orzhtml 请问下你是怎么解决这个问题的？

**Comment by orzhtml** [comment]
> @orzhtml 请问下你是怎么解决这个问题的？
安卓分享后返回app 闪退是因为缺少 wxapi/WXEntryActivity.java
