### ISSUE TITLE
集成时libWeChatSDK.a 没有复制到工程的

### ISSUE THREAD

**Issue by bluekurk** [yorkie/react-native-wechat#446]
问题描述: pod集成时没有真正将libWeChatSDK.a 加入到工程，造成的问题有可能有 1. 编译RCTWechat 时链接失败 2. 如果RCTWechat.h/m 没有引入，只是空pod的话，则运行时出现 evaluating 'WeChat.registerApp' 失败。3. 有时候编译报 xctest 失败

过程以及参考解决办法: 我的情况是在native里面嵌入rn，所以 Podfile 里是这样(:path 没试过, 不折腾了):

    pod 'RCTWeChat', :podspec => '../node_modules/react-native-wechat/ios/RCTWeChat.podspec'

然后把

     s.source_files  = "**/*.{h,m}"
     s.vendored_libraries = "libWeChatSDK.a"
     s.ios.frameworks = 'SystemConfiguration','CoreTelephony','XCTest'

修改为

     s.source_files  = 'ios/*.{h,m}'
     s.vendored_libraries = 'ios/libWeChatSDK.a'
     s.ios.frameworks = 'SystemConfiguration','CoreTelephony'

然后 Podfile 里先注释掉 pod install 然后再加回来再 pod install(否则可能直接 use 不刷新)，检查结果。

环境: macOS 10.13.6/XCode 10.1/react-native-wechat@^1.9.10/react-native@0.57.8

说明: 
1. 文件和库的路径多试几次，尽量用单引号，排除掉测试文件，确保库文件集成进来
2. XCTest 的引入，貌似是为了解决 s.source_files 不小心把 RCTWeChatTests.m 引入，它里面 import 了相关库。实际上这些东西应该在测试的 target 里处理吧，这里应该删掉。
[相关讨论](https://github.com/yorkie/react-native-wechat/pull/253)
3. 手动改库挺无奈的，谁勤快验证下，提个pr修改 RCTWeChat.podspec 吧
4. react-native link 后出 RCTBridgeModule.h 等一堆头文件找不到的问题，也没弄好，就按上面的办法用 cocoapods 处理了。ruby 不熟，不知道所以也没试过pod远程引用根目录下的 	react-native-wechat.podspec。总之希望官方出个faq什么的，节省大家时间。。。

**Comment by liumin1128** [comment]
同样的问题，求帮助

**Comment by liumin1128** [comment]
好几天了，没人管呢

**Comment by bluekurk** [comment]
参考解决办法
1. Podfile
  pod 'react-native-wechat', :git => 'https://github.com/weflex/react-native-wechat.git'
2. 如果用 swift, 需要在 header 文件里添加
#import <react_native_wechat/WXApi.h>
3. 完事。测试通过
