### ISSUE TITLE
sendAuthRequest > no response in Android

### ISSUE THREAD

**Issue by jcmlumacad** [yorkie/react-native-wechat#448]
![image](https://user-images.githubusercontent.com/21231662/55215582-3b1cd380-5235-11e9-8a0c-85dd3a0ac268.png)

`react-native-wechat version 1.9.10`

**Comment by michaelknoch** [comment]
have you found a workaround @jcmlumacad ? I think im also facing this issue

**Comment by jcmlumacad** [comment]
@michaelknoch not yet. Still finding some solutions.

**Comment by michaelknoch** [comment]
i noticed that i had to enable "android" in the wechat admin dashboard. After enabling it immediately works. @jcmlumacad
