### ISSUE TITLE
null is not an object (evaluating 'WeChat.registerApp')

### ISSUE THREAD

**Issue by hms111111** [yorkie/react-native-wechat#453]
救命啊,就没一个能用的吗?

**Comment by yangdachu** [comment]
@hms111111 这个问解决了吗？我今天也遇到了

**Comment by roynwang** [comment]
You may forget to link. run `react-native link`

**Comment by roynwang** [comment]
and then add some lib. Refer to https://github.com/yorkie/react-native-wechat/issues/439
