### ISSUE TITLE
undefined is not an object(evaluating 'v.registerApp')

### ISSUE THREAD

**Issue by ZengYingJ** [yorkie/react-native-wechat#465]

**Comment by yangdachu** [comment]
@ZengYingJ 这个问题你解决了吗

**Comment by yangdachu** [comment]
> 使用expo eject命令之后得到ios包，手动link之后还是报一样的错误。同样的手动link步骤不用expo，是成功的，想要使用expo的话真的没有办法了吗

我在expo里也遇到了这个问题
