### ISSUE TITLE
请教一下怎么把react-native-wechat集成到项目中啊？

### ISSUE THREAD

**Issue by KingAmo** [yorkie/react-native-wechat#469]
README中的集成教程也太简略了吧。。

**Comment by Y-io** [comment]
@KingAmo 集成很简单，只不过那个群永远都加不了，很多问题是集成后的

**Comment by KingAmo** [comment]
> @KingAmo 集成很简单，只不过那个群永远都加不了，很多问题是集成后的

是的，我加了好几次，没人同意一下。。

**Comment by byk04712** [comment]
别加群了，基本是个死群了，问问题也没人回答的。
