### ISSUE TITLE
微信支付闪退，没任何返回结果，现在不知道是前端配置问题还是后端给的参数有问题

### ISSUE THREAD

**Issue by wuweijian1997** [yorkie/react-native-wechat#476]
大佬们有什么办法验证后端给的参数是不是正确的吗？调用pay闪退，好像也没返回结果

**Comment by wuweijian1997** [comment]
已经解决了支付bug，简单记一下容易报错的地方。
1.
![image](https://user-images.githubusercontent.com/29529286/60644976-148cbb00-9e6a-11e9-9335-b8f00ece8b56.png)
这一般就是应用签名错误，获取应用签名的方法有很多，微信的工具app还有Androidstudio都可以获取，
如果微信分享和登录没问题的话应用签名就没问题。
2.
点击支付闪退，报错Wechat Error code: -1,
这首先按照readme的配置一遍，也有很大的可能是后端给的数据错误，我这弄了两天最后发现是后端生成的sign是错误的。。。。
具体可以看 [https://blog.csdn.net/nnmmbb/article/details/50533138](url)，不止是前端的那部分，后端的那部分也仔细看一下。
3.其实也可以在模拟器调式微信支付，
获取应用程序的dubug 应用签名，微信开发平台设置debug版的应用签名就可以了。
![image](https://user-images.githubusercontent.com/29529286/60645982-bf9e7400-9e6c-11e9-964a-17fd3b2e1c5e.png)
然后在模拟器里下载个微信就可以了。（我用的是夜神模拟器）

或者也可以用发布版的应用签名，然后使用 
react-native run-android --variant=release
编译发布版的应用，运行这命令之前需要卸载之前的app。

如果确定前端这边和readme写的都差不多的话最好再确认一下后端生成的sign是否正确，如果后端给的数据有问题，前端怎么调都解决不了碰到的问题。

**Comment by cnpmge** [comment]
大佬，你是怎么解决闪退问题的？我跳到了支付页，取消支付和输入密码后确认支付都会造成app的闪退
