### ISSUE TITLE
Add issue report template or guide (建议在issues输入框给到issues反馈引导提示)

### ISSUE THREAD

**Issue by M1seRy** [yorkie/react-native-wechat#495]
I find many issues need more information and descriptions, maybe we can add issue report template to solve this problem。For example：

1. Bug Report or Documentation Issue or Questions and Help ?

2. Which `react-native-wechat` version are you using?

3. What platform does your issue occur on? (Android/iOS/Both)

4. Please provide a clear and concise description of what the bug is as precisely as possible，you can  : 
  1) post a screenshot to explain in which case you get the issue？
  2) related `logs`？
  3) show us the code you are using?

### Your Environment

| software         | version
| ---------------- | -------
| react-native-wechat |  ^ version
| react-native     | ^ version
| node             | ^ version
| npm or yarn      | ^ version

others

**Comment by yorkie** [comment]
This LGTM, would you please create a PR for this project?

**Comment by M1seRy** [comment]
@yorkie  check this pr [#501](https://github.com/yorkie/react-native-wechat/pull/501)
