### ISSUE TITLE
包名不对，请检查包名是否与开放平台上填写的一致

### ISSUE THREAD

**Issue by XPgan** [yorkie/react-native-wechat#505]
applicationId 包名  和  开放平台上填写的一样，
签名通过微信开发平台的工具获取的签名 一样  获取的小写  换成大写 每个2个就加一个 ：(例如 : a23dad => A2:3D:AD）

| react-native-wechat |  ^1.9.10
| react-native     | ^ 0.59.8

**Comment by ForevereBest** [comment]
请问你是怎么解决的？
