### ISSUE TITLE
case-sensitive paths on a case-insensitive filesystem Example 例子名称重复

### ISSUE THREAD

**Issue by M1seRy** [yorkie/react-native-wechat#512]
git pull 拉最新的代码时提示：

```log
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'Example/README.md'
  'example/README.md'

```

提示大小写敏感，之前的更新是在 Example 基础上做的，现在看到主分支上有 `Example` 和 `example` 两个例子，是 pr 合并出了问题？@yorkie

版本信息:

当前最新版本。

**Comment by yorkie** [comment]
不好意思才看到，应该是 138f4f8edac0edf9147ca139c4452cef62919260 导致的问题，因为之前的都是大写的，然后后面新加的文件是小写的 example，你重新克隆（Clone）还会有这个问题吗？

**Comment by yorkie** [comment]
我本地试了一下，没有出现警告：

```sh
git clone git@github.com:yorkie/react-native-wechat.git
Cloning into 'react-native-wechat'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 3658 (delta 4), reused 8 (delta 2), pack-reused 3643
Receiving objects: 100% (3658/3658), 52.30 MiB | 444.00 KiB/s, done.
Resolving deltas: 100% (1271/1271), done.
```

不过克隆下来是 Example，跟 GitHub 显示的不同，是不是可以换个目录，比如 playground 这样的？

**Comment by M1seRy** [comment]
@yorkie 我删除了 GitHub 上的仓库，重新 fork 后，再 clone 到本地，还是同样的问题，而且目录下只会显示一个 Example。我建议保留一个，可以把之前的旧 Example 移除，如果需要保留两个，可以将 example 文件夹更换一个名字，例如 example-rn-0.60，这样应该不会出现混淆的情况。

**Comment by yorkie** [comment]
嗯，我建议换名字吧，playground 是不是更好一些，例子本身包含 RN 的版本号不太好，并且统一用小写吧。

**Comment by M1seRy** [comment]
> 嗯，我建议换名字吧，playground 是不是更好一些，例子本身包含 RN 的版本号不太好，并且统一用小写吧。

OK的，能区分一下就好。

**Comment by yorkie** [comment]
嗯嗯 这样很赞～

**Comment by M1seRy** [comment]
@yorkie  check [pr519](https://github.com/yorkie/react-native-wechat/pull/519)
