### ISSUE TITLE
ios授权登录闪退

### ISSUE THREAD

**Issue by zgjYswor** [yorkie/react-native-wechat#523]
ios版本是12.2
机型是 iPhone 6sp和 iPhone 7p

### Your Environment

| software         | version
| ---------------- | -------
| react-native-wechat |  ^ 1.9.11
| react-native |  0.60.5

[闪退视频](https://cdn.ijustplay.cn/files/1570535334913272.mp4)

相关代码
```
WeChat.sendAuthRequest('snsapi_userinfo')
      .then(async (data: WeChat.AuthResponse) => {
        if (data.code) {
           ......
        } else {
          Alert.alert('微信登录失败')
        }
      })
      .catch(err => {
        console.log('err is ', err)
      })
```

**Comment by M1seRy** [comment]
@zgjYswor 方便真机调试吗？给到 crash 报错的日志信息。

**Comment by zgjYswor** [comment]
> @zgjYswor 方便真机调试吗？给到 crash 报错的日志信息。

发现code正常拿到了, 是在下一步调用请求库的时候请求库出错了
