### ISSUE TITLE
老兄啊，这个库的微信SDK版本太低了，抽时间更新下吧

### ISSUE THREAD

**Issue by idbeny** [yorkie/react-native-wechat#525]

**Comment by M1seRy** [comment]
duplicate [#521](https://github.com/yorkie/react-native-wechat/issues/521) [#511](https://github.com/yorkie/react-native-wechat/issues/511)

**Comment by 0xinhua** [comment]
Hi @idbeny SDK 更新进度统一对齐到 [#521](https://github.com/yorkie/react-native-wechat/issues/521) 及 [#PR526](https://github.com/yorkie/react-native-wechat/pull/526)
这个 issues 先关闭了，后续你更新使用如有问题可以随时再打开 ：）
