### ISSUE TITLE
微信支付返回-1，不能调起微信是什么原因？

### ISSUE THREAD

**Issue by Young1006** [yorkie/react-native-wechat#529]
{ [WechatError: -1]
      name: 'WechatError',
      code: -1,
      line: 137380,
      column: 28,
      sourceURL: 'http://localhost:8081/index.delta?platform=android&dev=true&minify=false' }

**Comment by 0xinhua** [comment]
@NewYoungPG 先看下这几个 issues [#356 ](https://github.com/yorkie/react-native-wechat/issues/356 ) [#220](https://github.com/yorkie/react-native-wechat/issues/220) 是否是同样的问题。

**Comment by Young1006** [comment]
解决了，是签名的问题！

**Comment by quanzaiyu** [comment]
@NewYoungPG 我也是报 -1, 然后闪了一下就没了, 请问下你是怎么解决的
这是调用方式:
![image](https://user-images.githubusercontent.com/13745132/68107916-3635a600-ff21-11e9-8510-b985d0e5ba18.png)
其中 payInfo 是获取到的参数:
![image](https://user-images.githubusercontent.com/13745132/68109119-bc072080-ff24-11e9-83bd-82635a3b67a2.png)
麻烦你帮忙看下传递的参数格式是不是正确的, 如果正确的话, 我再检查下其他地方的配置是否正确

**Comment by quanzaiyu** [comment]
我感觉package不是这样传的, 但微信支付文档就是这种样子, 就是 'Sign=WXPay', 但看这插件的注释好像又不是

**Comment by Young1006** [comment]
具体的我也看不出来，不知道signtype这个参数好像有问题。如果调不起微信，你要去看看微信开放平台里面看一下签名是否正确



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xiaoyu"<notifications@github.com&gt;; 
发送时间: 2019年11月4日(星期一) 下午4:39
收件人: "yorkie/react-native-wechat"<react-native-wechat@noreply.github.com&gt;; 
抄送: "NewYoung"<754515065@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [yorkie/react-native-wechat] 微信支付返回-1，不能调起微信是什么原因？ (#529)




@NewYoungPG 我也是报 -1, 然后闪了一下就没了, 请问下你是怎么解决的
 这是调用方式:
 
 其中 payInfo 是获取到的参数:
 
 麻烦你帮忙看下传递的参数格式是不是正确的, 如果正确的话, 我再检查下其他地方的配置是否正确

**Comment by quanzaiyu** [comment]
微信开放平台的配置保证是正确的, 签名就是用微信的那个签名apk做的, 做的是release版的签名, signType 后端数据是返回了但在这里面并没有用到, 有可能是后端签名的问题。 但只有在APP中调不起支付, 试过uni-app调取支付也不行, 但在JSSDK、扫码支付、小程序支付和H5中支付都没问题, 郁闷
