### ISSUE TITLE
分享到微信后，点击返回App按钮并没有返回去，只是页面关闭了并停留在微信里。

### ISSUE THREAD

**Issue by regon-cao** [yorkie/react-native-wechat#535]
分享到微信后，点击返回App按钮并没有返回去，只是页面关闭了并停留在微信里。有人知道为什么吗。同一套代码在其余的App里都正常，所以怀疑跟微信新添加的Universal Links有关（有异常的是在微信开放平台新申请的appid）

**Comment by 0xinhua** [comment]
@regon-cao 可以提供这个问题的更多信息吗？出错平台（iOS or Android or both）、RN 版本、集成的 react-native-wechat 版本等。

**Comment by regon-cao** [comment]
IOS有问题，RN版本0.45  react-native-wechat版本1.9.9

**Comment by regon-cao** [comment]
ios URL TYPES配置错误，已解决。
