### ISSUE TITLE
0.62.1安卓微信无法回调

### ISSUE THREAD

**Issue by mengerzhuanyong** [yorkie/react-native-wechat#557]
### Your Environment

| software         | version
| ---------------- | -------
| react-native-wechat |  ^ 1.9.12
| react-native     | ^ 0.62.1
| node             | ^ 12.10.0
| npm or yarn      | ^ 6.14.4 / 1.21.1

安卓可以唤起，无法回调，控制台信息
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
W/InputMethodManager: startInputReason = 1

**Comment by chocolateonly** [comment]
I have same issue

**Comment by mengerzhuanyong** [comment]
检查一下项目包名和项目的applicationId是否一致，不一致的情况下就会出现这样的问题！～

**Comment by whereiscode** [comment]
@mengerzhuanyong 按您说的 bug依然存在 0.60 以下老版本不存在
