### ISSUE TITLE
现在在苹果端如果微信SDK包含支付功能审核是不会通过的，这个怎么解决？

### ISSUE THREAD

**Issue by Liqiankun** [yorkie/react-native-wechat#569]

**Comment by Liqiankun** [comment]
我现在的方法是在[微信资源下载](https://developers.weixin.qq.com/doc/oplatform/Downloads/iOS_Resource.html)中下载不包含支付的SDK替换掉。

**Comment by 18023277291** [comment]
你的问题解决了吗！我按照你说的替换了最新的SDK也不行！

**Comment by Liqiankun** [comment]
@18023277291 解决这个问题还是很复杂，因为你下载新的SDK，接口已经变了。我单独发给你一个我修改好的。你的邮箱。

**Comment by jessietang** [comment]
@Liqiankun 请问你最后怎么解决的呢？

**Comment by Liqiankun** [comment]
ios还是需要改很多的，一个是用[微信资源下载](https://developers.weixin.qq.com/doc/oplatform/Downloads/iOS_Resource.html)中下载不包含支付的SDK替换掉。然后去修改React Native代码，还要搞定[APP之Universal Link](https://www.jianshu.com/p/ab50bdaec65d)
